# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../joliebulle/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(472, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Preferences)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBoxBoilOff = QtWidgets.QSpinBox(self.tab)
        self.spinBoxBoilOff.setObjectName("spinBoxBoilOff")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxBoilOff)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBoxCooling = QtWidgets.QSpinBox(self.tab)
        self.spinBoxCooling.setObjectName("spinBoxCooling")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxCooling)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBoxGrainTemp = QtWidgets.QSpinBox(self.tab)
        self.spinBoxGrainTemp.setObjectName("spinBoxGrainTemp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxGrainTemp)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBoxFudgeFactor = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxFudgeFactor.setObjectName("doubleSpinBoxFudgeFactor")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxFudgeFactor)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBoxGrainRetention = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxGrainRetention.setObjectName("doubleSpinBoxGrainRetention")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxGrainRetention)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.Bibliotheque = QtWidgets.QWidget()
        self.Bibliotheque.setObjectName("Bibliotheque")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Bibliotheque)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.Bibliotheque)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditPathLib = QtWidgets.QLineEdit(self.Bibliotheque)
        self.lineEditPathLib.setObjectName("lineEditPathLib")
        self.horizontalLayout.addWidget(self.lineEditPathLib)
        self.pushButtonChangeLib = QtWidgets.QPushButton(self.Bibliotheque)
        self.pushButtonChangeLib.setObjectName("pushButtonChangeLib")
        self.horizontalLayout.addWidget(self.pushButtonChangeLib)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_7 = QtWidgets.QLabel(self.Bibliotheque)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.Bibliotheque, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.buttonBox.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Preferences.accept)
        self.buttonBox.rejected.connect(Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Préférences"))
        self.label_2.setText(_translate("Preferences", "Taux d\'évaporation (%/h) :"))
        self.label_3.setText(_translate("Preferences", "Pertes par refroidissement (%) :"))
        self.label_4.setText(_translate("Preferences", "Température du grain :"))
        self.label_5.setText(_translate("Preferences", "Facteur de correction des températures :"))
        self.label_6.setText(_translate("Preferences", "Rétention d\'eau par le grain (l/kg) :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Preferences", "Brassage"))
        self.label.setText(_translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Emplacement de la bibliothèque : </span></p></body></html>"))
        self.pushButtonChangeLib.setText(_translate("Preferences", "Changer"))
        self.label_7.setText(_translate("Preferences", "Attention ! Utilisez un répertoire qui ne contient que des recettes."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Bibliotheque), _translate("Preferences", "Bibliothèque"))

