# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../joliebulle/reader.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 771)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/bulle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.webViewBiblio = QtWebKitWidgets.QWebView(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewBiblio.sizePolicy().hasHeightForWidth())
        self.webViewBiblio.setSizePolicy(sizePolicy)
        self.webViewBiblio.setProperty("url", QtCore.QUrl("about:blank"))
        self.webViewBiblio.setObjectName("webViewBiblio")
        self.verticalLayout_13.addWidget(self.webViewBiblio)
        self.horizontalLayout_20.addLayout(self.verticalLayout_13)
        self.gridLayout_13.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.webViewBrewday = QtWebKitWidgets.QWebView(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewBrewday.sizePolicy().hasHeightForWidth())
        self.webViewBrewday.setSizePolicy(sizePolicy)
        self.webViewBrewday.setProperty("url", QtCore.QUrl("about:blank"))
        self.webViewBrewday.setObjectName("webViewBrewday")
        self.gridLayout_2.addWidget(self.webViewBrewday, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_8.setContentsMargins(-1, 18, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(9, -1, 9, 6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listWidgetMashProfiles = QtWidgets.QListWidget(self.page_4)
        self.listWidgetMashProfiles.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetMashProfiles.setProperty("isWrapping", False)
        self.listWidgetMashProfiles.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidgetMashProfiles.setObjectName("listWidgetMashProfiles")
        self.verticalLayout_8.addWidget(self.listWidgetMashProfiles)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonRemoveProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonRemoveProfile.setEnabled(False)
        self.pushButtonRemoveProfile.setObjectName("pushButtonRemoveProfile")
        self.horizontalLayout_9.addWidget(self.pushButtonRemoveProfile)
        self.pushButtonNewProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonNewProfile.setObjectName("pushButtonNewProfile")
        self.horizontalLayout_9.addWidget(self.pushButtonNewProfile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.widget = QtWidgets.QWidget(self.page_4)
        self.widget.setMinimumSize(QtCore.QSize(500, 0))
        self.widget.setObjectName("widget")
        self.formLayout_7 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(50, -1, 50, -1)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.labelMashName = QtWidgets.QLabel(self.widget)
        self.labelMashName.setObjectName("labelMashName")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelMashName)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.labelMashPh = QtWidgets.QLabel(self.widget)
        self.labelMashPh.setObjectName("labelMashPh")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelMashPh)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.labelMashSpargeTemp = QtWidgets.QLabel(self.widget)
        self.labelMashSpargeTemp.setObjectName("labelMashSpargeTemp")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelMashSpargeTemp)
        self.pushButtonMashEdit = QtWidgets.QPushButton(self.widget)
        self.pushButtonMashEdit.setEnabled(False)
        self.pushButtonMashEdit.setObjectName("pushButtonMashEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButtonMashEdit)
        self.horizontalLayout_14.addWidget(self.widget)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetSteps = QtWidgets.QListWidget(self.page_4)
        self.listWidgetSteps.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetSteps.setObjectName("listWidgetSteps")
        self.verticalLayout_2.addWidget(self.listWidgetSteps)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonStepRemove = QtWidgets.QPushButton(self.page_4)
        self.pushButtonStepRemove.setEnabled(False)
        self.pushButtonStepRemove.setObjectName("pushButtonStepRemove")
        self.horizontalLayout_6.addWidget(self.pushButtonStepRemove)
        self.pushButtonNewStep = QtWidgets.QPushButton(self.page_4)
        self.pushButtonNewStep.setObjectName("pushButtonNewStep")
        self.horizontalLayout_6.addWidget(self.pushButtonNewStep)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.page_4)
        self.widget1.setMinimumSize(QtCore.QSize(500, 0))
        self.widget1.setObjectName("widget1")
        self.formLayout_6 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(50, -1, 50, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.labelStepName = QtWidgets.QLabel(self.widget1)
        self.labelStepName.setObjectName("labelStepName")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelStepName)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.labelStepType = QtWidgets.QLabel(self.widget1)
        self.labelStepType.setObjectName("labelStepType")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelStepType)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.labelStepTime = QtWidgets.QLabel(self.widget1)
        self.labelStepTime.setObjectName("labelStepTime")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelStepTime)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.labelStepTemp = QtWidgets.QLabel(self.widget1)
        self.labelStepTemp.setObjectName("labelStepTemp")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelStepTemp)
        self.pushButtonStepEdit = QtWidgets.QPushButton(self.widget1)
        self.pushButtonStepEdit.setEnabled(False)
        self.pushButtonStepEdit.setObjectName("pushButtonStepEdit")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonStepEdit)
        self.horizontalLayout_8.addWidget(self.widget1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.buttonBoxMashDetails = QtWidgets.QDialogButtonBox(self.page_4)
        self.buttonBoxMashDetails.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBoxMashDetails.setObjectName("buttonBoxMashDetails")
        self.horizontalLayout_15.addWidget(self.buttonBoxMashDetails)
        self.pushButtonSaveProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonSaveProfile.setObjectName("pushButtonSaveProfile")
        self.horizontalLayout_15.addWidget(self.pushButtonSaveProfile)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.gridLayout_8.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1238, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuFichier = QtWidgets.QMenu(self.menuBar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuIngr_dients = QtWidgets.QMenu(self.menuBar)
        self.menuIngr_dients.setObjectName("menuIngr_dients")
        self.menuOutils = QtWidgets.QMenu(self.menuBar)
        self.menuOutils.setObjectName("menuOutils")
        self.menuEdition = QtWidgets.QMenu(self.menuBar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuAide = QtWidgets.QMenu(self.menuBar)
        self.menuAide.setObjectName("menuAide")
        self.menuProfils_de_brassage = QtWidgets.QMenu(self.menuBar)
        self.menuProfils_de_brassage.setObjectName("menuProfils_de_brassage")
        self.menuJOurnal = QtWidgets.QMenu(self.menuBar)
        self.menuJOurnal.setObjectName("menuJOurnal")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOuvrir.setIcon(icon1)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon2)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer.setEnabled(False)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_Sous = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Sous.setEnabled(False)
        self.actionEnregistrer_Sous.setObjectName("actionEnregistrer_Sous")
        self.actionQuitter_2 = QtWidgets.QAction(MainWindow)
        self.actionQuitter_2.setObjectName("actionQuitter_2")
        self.actionOuvrir_2 = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_2.setObjectName("actionOuvrir_2")
        self.actionEditGrains = QtWidgets.QAction(MainWindow)
        self.actionEditGrains.setObjectName("actionEditGrains")
        self.actionEditHoublons = QtWidgets.QAction(MainWindow)
        self.actionEditHoublons.setObjectName("actionEditHoublons")
        self.actionEditDivers = QtWidgets.QAction(MainWindow)
        self.actionEditDivers.setObjectName("actionEditDivers")
        self.actionEditLevures = QtWidgets.QAction(MainWindow)
        self.actionEditLevures.setObjectName("actionEditLevures")
        self.actionNouvelle_recette = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNouvelle_recette.setIcon(icon4)
        self.actionNouvelle_recette.setObjectName("actionNouvelle_recette")
        self.actionCorrectionDens = QtWidgets.QAction(MainWindow)
        self.actionCorrectionDens.setObjectName("actionCorrectionDens")
        self.actionCalculAlc = QtWidgets.QAction(MainWindow)
        self.actionCalculAlc.setObjectName("actionCalculAlc")
        self.actionImprimer = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer.setIcon(icon5)
        self.actionImprimer.setObjectName("actionImprimer")
        self.actionDilution = QtWidgets.QAction(MainWindow)
        self.actionDilution.setObjectName("actionDilution")
        self.actionEvaporation = QtWidgets.QAction(MainWindow)
        self.actionEvaporation.setObjectName("actionEvaporation")
        self.actionExporterHtml = QtWidgets.QAction(MainWindow)
        self.actionExporterHtml.setEnabled(False)
        self.actionExporterHtml.setObjectName("actionExporterHtml")
        self.actionPaliers = QtWidgets.QAction(MainWindow)
        self.actionPaliers.setObjectName("actionPaliers")
        self.actionRestaurerIngredients = QtWidgets.QAction(MainWindow)
        self.actionRestaurerIngredients.setObjectName("actionRestaurerIngredients")
        self.actionRecharger = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecharger.setIcon(icon6)
        self.actionRecharger.setObjectName("actionRecharger")
        self.actionSwitch = QtWidgets.QAction(MainWindow)
        self.actionSwitch.setObjectName("actionSwitch")
        self.actionVueEditeur = QtWidgets.QAction(MainWindow)
        self.actionVueEditeur.setObjectName("actionVueEditeur")
        self.actionVueBibliotheque = QtWidgets.QAction(MainWindow)
        self.actionVueBibliotheque.setObjectName("actionVueBibliotheque")
        self.actionVueEditeurToolBar = QtWidgets.QAction(MainWindow)
        self.actionVueEditeurToolBar.setCheckable(True)
        self.actionVueEditeurToolBar.setChecked(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueEditeurToolBar.setIcon(icon7)
        self.actionVueEditeurToolBar.setObjectName("actionVueEditeurToolBar")
        self.actionVueBibliothequeToolBar = QtWidgets.QAction(MainWindow)
        self.actionVueBibliothequeToolBar.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Images/library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueBibliothequeToolBar.setIcon(icon8)
        self.actionVueBibliothequeToolBar.setObjectName("actionVueBibliothequeToolBar")
        self.actionEnregistrerToolBar = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrerToolBar.setIcon(icon9)
        self.actionEnregistrerToolBar.setObjectName("actionEnregistrerToolBar")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionBrewdayMode = QtWidgets.QAction(MainWindow)
        self.actionBrewdayMode.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/brewday.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrewdayMode.setIcon(icon10)
        self.actionBrewdayMode.setObjectName("actionBrewdayMode")
        self.actionNouveau_Dossier = QtWidgets.QAction(MainWindow)
        self.actionNouveau_Dossier.setObjectName("actionNouveau_Dossier")
        self.actionNouvelle_recette_2 = QtWidgets.QAction(MainWindow)
        self.actionNouvelle_recette_2.setObjectName("actionNouvelle_recette_2")
        self.actionImporter = QtWidgets.QAction(MainWindow)
        self.actionImporter.setObjectName("actionImporter")
        self.actionCopierBbcode = QtWidgets.QAction(MainWindow)
        self.actionCopierBbcode.setEnabled(False)
        self.actionCopierBbcode.setObjectName("actionCopierBbcode")
        self.actionManageProfiles = QtWidgets.QAction(MainWindow)
        self.actionManageProfiles.setObjectName("actionManageProfiles")
        self.actionImportIng = QtWidgets.QAction(MainWindow)
        self.actionImportIng.setObjectName("actionImportIng")
        self.actionShowJournal = QtWidgets.QAction(MainWindow)
        self.actionShowJournal.setObjectName("actionShowJournal")
        self.actionEditJournal = QtWidgets.QAction(MainWindow)
        self.actionEditJournal.setEnabled(True)
        self.actionEditJournal.setObjectName("actionEditJournal")
        self.actionAllTools = QtWidgets.QAction(MainWindow)
        self.actionAllTools.setObjectName("actionAllTools")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuIngr_dients.addAction(self.actionEditGrains)
        self.menuIngr_dients.addAction(self.actionEditHoublons)
        self.menuIngr_dients.addAction(self.actionEditDivers)
        self.menuIngr_dients.addAction(self.actionEditLevures)
        self.menuIngr_dients.addAction(self.actionRestaurerIngredients)
        self.menuIngr_dients.addAction(self.actionImportIng)
        self.menuOutils.addAction(self.actionAllTools)
        self.menuEdition.addAction(self.actionPreferences)
        self.menuAide.addAction(self.actionAbout)
        self.menuProfils_de_brassage.addAction(self.actionManageProfiles)
        self.menuJOurnal.addAction(self.actionShowJournal)
        self.menuBar.addAction(self.menuFichier.menuAction())
        self.menuBar.addAction(self.menuEdition.menuAction())
        self.menuBar.addAction(self.menuIngr_dients.menuAction())
        self.menuBar.addAction(self.menuJOurnal.menuAction())
        self.menuBar.addAction(self.menuProfils_de_brassage.menuAction())
        self.menuBar.addAction(self.menuOutils.menuAction())
        self.menuBar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JolieBulle"))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Profils de brassage :</span></p></body></html>"))
        self.pushButtonRemoveProfile.setText(_translate("MainWindow", "Enlever"))
        self.pushButtonNewProfile.setText(_translate("MainWindow", "Nouveau profil"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Nom :</span></p></body></html>"))
        self.labelMashName.setText(_translate("MainWindow", "Aucun"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">pH :</span></p></body></html>"))
        self.labelMashPh.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Rinçage :</span></p></body></html>"))
        self.labelMashSpargeTemp.setText(_translate("MainWindow", "0 °C"))
        self.pushButtonMashEdit.setText(_translate("MainWindow", "Modifier"))
        self.label_14.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Paliers :</span></p></body></html>"))
        self.pushButtonStepRemove.setText(_translate("MainWindow", "Enlever"))
        self.pushButtonNewStep.setText(_translate("MainWindow", "Nouveau palier"))
        self.label_9.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nom :</span></p></body></html>"))
        self.labelStepName.setText(_translate("MainWindow", "Aucun"))
        self.label_10.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Type :</span></p></body></html>"))
        self.labelStepType.setText(_translate("MainWindow", "Aucun"))
        self.label_11.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Durée :</span></p></body></html>"))
        self.labelStepTime.setText(_translate("MainWindow", "0 min"))
        self.label_12.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Température :</span></p></body></html>"))
        self.labelStepTemp.setText(_translate("MainWindow", "0 °C"))
        self.pushButtonStepEdit.setText(_translate("MainWindow", "Modifier"))
        self.pushButtonSaveProfile.setText(_translate("MainWindow", "Enregistrer les profils"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuIngr_dients.setTitle(_translate("MainWindow", "Ingrédients"))
        self.menuOutils.setTitle(_translate("MainWindow", "Outils"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.menuProfils_de_brassage.setTitle(_translate("MainWindow", "Profils de brassage"))
        self.menuJOurnal.setTitle(_translate("MainWindow", "Journal"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionAbout.setText(_translate("MainWindow", "A propos"))
        self.actionEnregistrer.setText(_translate("MainWindow", "&Enregistrer"))
        self.actionEnregistrer_Sous.setText(_translate("MainWindow", "Enregistrer &sous"))
        self.actionQuitter_2.setText(_translate("MainWindow", "Quitter"))
        self.actionOuvrir_2.setText(_translate("MainWindow", "&Ouvrir"))
        self.actionEditGrains.setText(_translate("MainWindow", "Editer la base de Grains"))
        self.actionEditHoublons.setText(_translate("MainWindow", "Editer la base de Houblons"))
        self.actionEditDivers.setText(_translate("MainWindow", "Editer la base de Divers"))
        self.actionEditLevures.setText(_translate("MainWindow", "Editer la base de Levures"))
        self.actionNouvelle_recette.setText(_translate("MainWindow", "Nouvelle recette"))
        self.actionCorrectionDens.setText(_translate("MainWindow", "Correction densimètre"))
        self.actionCalculAlc.setText(_translate("MainWindow", "Calcul taux d\'alcool"))
        self.actionImprimer.setText(_translate("MainWindow", "Imprimer"))
        self.actionDilution.setText(_translate("MainWindow", "Dilution"))
        self.actionEvaporation.setText(_translate("MainWindow", "Evaporation"))
        self.actionExporterHtml.setText(_translate("MainWindow", "Exporter vers html"))
        self.actionPaliers.setText(_translate("MainWindow", "Assistant paliers"))
        self.actionRestaurerIngredients.setText(_translate("MainWindow", "Restaurer la base des ingrédients"))
        self.actionRecharger.setText(_translate("MainWindow", "Recharger"))
        self.actionSwitch.setText(_translate("MainWindow", "switch"))
        self.actionVueEditeur.setText(_translate("MainWindow", "Editeur de recettes"))
        self.actionVueBibliotheque.setText(_translate("MainWindow", "Bibliothèque de recettes"))
        self.actionVueBibliotheque.setToolTip(_translate("MainWindow", "Bibiliothèque de recettes"))
        self.actionVueEditeurToolBar.setText(_translate("MainWindow", "Editeur"))
        self.actionVueBibliothequeToolBar.setText(_translate("MainWindow", "Bibiliothèque"))
        self.actionVueBibliothequeToolBar.setToolTip(_translate("MainWindow", "Bibiliothèque de recettes"))
        self.actionEnregistrerToolBar.setText(_translate("MainWindow", "&Enregistrer"))
        self.actionPreferences.setText(_translate("MainWindow", "Préférences"))
        self.actionBrewdayMode.setText(_translate("MainWindow", "Brassage"))
        self.actionBrewdayMode.setToolTip(_translate("MainWindow", "Mode brassage"))
        self.actionNouveau_Dossier.setText(_translate("MainWindow", "Nouveau dossier"))
        self.actionNouveau_Dossier.setToolTip(_translate("MainWindow", "Créer un nouveau dossier dans la bibliothèque"))
        self.actionNouvelle_recette_2.setText(_translate("MainWindow", "Nouvelle recette"))
        self.actionNouvelle_recette_2.setToolTip(_translate("MainWindow", "Créer une nouvelle recette"))
        self.actionImporter.setText(_translate("MainWindow", "Importer une recette"))
        self.actionCopierBbcode.setText(_translate("MainWindow", "Copier le BBCode (format forum) dans le presse papier"))
        self.actionManageProfiles.setText(_translate("MainWindow", "Gérer les profils"))
        self.actionImportIng.setText(_translate("MainWindow", "Importer des ingrédients"))
        self.actionShowJournal.setText(_translate("MainWindow", "Ouvrir le journal"))
        self.actionEditJournal.setText(_translate("MainWindow", "Ajouter une entrée"))
        self.actionAllTools.setText(_translate("MainWindow", "Tous les outils"))

from PyQt5 import QtWebKitWidgets
import ressources_rc
