# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../joliebulle/window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/bulle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetEditeur = QtWidgets.QWidget(self.page)
        self.widgetEditeur.setObjectName("widgetEditeur")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetEditeur)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxIng = QtWidgets.QCheckBox(self.widgetEditeur)
        self.checkBoxIng.setObjectName("checkBoxIng")
        self.horizontalLayout_5.addWidget(self.checkBoxIng)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButtonChangeIngredients = QtWidgets.QPushButton(self.widgetEditeur)
        self.pushButtonChangeIngredients.setCheckable(True)
        self.pushButtonChangeIngredients.setObjectName("pushButtonChangeIngredients")
        self.horizontalLayout_5.addWidget(self.pushButtonChangeIngredients)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBoxMashProfiles = QtWidgets.QComboBox(self.widgetEditeur)
        self.comboBoxMashProfiles.setMinimumSize(QtCore.QSize(400, 0))
        self.comboBoxMashProfiles.setObjectName("comboBoxMashProfiles")
        self.horizontalLayout_3.addWidget(self.comboBoxMashProfiles)
        self.pushButtonMashDetails = QtWidgets.QPushButton(self.widgetEditeur)
        self.pushButtonMashDetails.setObjectName("pushButtonMashDetails")
        self.horizontalLayout_3.addWidget(self.pushButtonMashDetails)
        self.pushButtonBrewdayMode = QtWidgets.QPushButton(self.widgetEditeur)
        self.pushButtonBrewdayMode.setObjectName("pushButtonBrewdayMode")
        self.horizontalLayout_3.addWidget(self.pushButtonBrewdayMode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.widgetIngredients = QtWidgets.QWidget(self.widgetEditeur)
        self.widgetIngredients.setObjectName("widgetIngredients")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widgetIngredients)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBox = QtWidgets.QComboBox(self.widgetIngredients)
        self.comboBox.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.pushButtonAjouter_2 = QtWidgets.QPushButton(self.widgetIngredients)
        self.pushButtonAjouter_2.setObjectName("pushButtonAjouter_2")
        self.horizontalLayout_10.addWidget(self.pushButtonAjouter_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBoxH = QtWidgets.QComboBox(self.widgetIngredients)
        self.comboBoxH.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxH.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxH.setObjectName("comboBoxH")
        self.horizontalLayout_11.addWidget(self.comboBoxH)
        self.pushButtonAjouterH = QtWidgets.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterH.setObjectName("pushButtonAjouterH")
        self.horizontalLayout_11.addWidget(self.pushButtonAjouterH)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.comboBoxM = QtWidgets.QComboBox(self.widgetIngredients)
        self.comboBoxM.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxM.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxM.setObjectName("comboBoxM")
        self.horizontalLayout_12.addWidget(self.comboBoxM)
        self.pushButtonAjouterM = QtWidgets.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterM.setObjectName("pushButtonAjouterM")
        self.horizontalLayout_12.addWidget(self.pushButtonAjouterM)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.comboBoxY = QtWidgets.QComboBox(self.widgetIngredients)
        self.comboBoxY.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxY.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxY.setObjectName("comboBoxY")
        self.horizontalLayout_13.addWidget(self.comboBoxY)
        self.pushButtonAjouterY = QtWidgets.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterY.setObjectName("pushButtonAjouterY")
        self.horizontalLayout_13.addWidget(self.pushButtonAjouterY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButtonEnlever = QtWidgets.QPushButton(self.widgetIngredients)
        self.pushButtonEnlever.setObjectName("pushButtonEnlever")
        self.horizontalLayout_7.addWidget(self.pushButtonEnlever)
        self.gridLayout_7.addWidget(self.widgetIngredients, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelRecette = QtWidgets.QLabel(self.widgetEditeur)
        self.labelRecette.setObjectName("labelRecette")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelRecette)
        self.lineEditRecette = QtWidgets.QLineEdit(self.widgetEditeur)
        self.lineEditRecette.setObjectName("lineEditRecette")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditRecette)
        self.labelGenre = QtWidgets.QLabel(self.widgetEditeur)
        self.labelGenre.setObjectName("labelGenre")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelGenre)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditGenre = QtWidgets.QLineEdit(self.widgetEditeur)
        self.lineEditGenre.setObjectName("lineEditGenre")
        self.horizontalLayout.addWidget(self.lineEditGenre)
        self.pushButtonChangerStyle = QtWidgets.QPushButton(self.widgetEditeur)
        self.pushButtonChangerStyle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/document-properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonChangerStyle.setIcon(icon1)
        self.pushButtonChangerStyle.setCheckable(True)
        self.pushButtonChangerStyle.setObjectName("pushButtonChangerStyle")
        self.horizontalLayout.addWidget(self.pushButtonChangerStyle)
        self.comboBoxStyle = QtWidgets.QComboBox(self.widgetEditeur)
        self.comboBoxStyle.setObjectName("comboBoxStyle")
        self.horizontalLayout.addWidget(self.comboBoxStyle)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(20, -1, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widgetEditeur)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditBrewer = QtWidgets.QLineEdit(self.widgetEditeur)
        self.lineEditBrewer.setObjectName("lineEditBrewer")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditBrewer)
        self.label_4 = QtWidgets.QLabel(self.widgetEditeur)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBoxType = QtWidgets.QComboBox(self.widgetEditeur)
        self.comboBoxType.setObjectName("comboBoxType")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxType)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.labelFermentables = QtWidgets.QLabel(self.widgetEditeur)
        self.labelFermentables.setObjectName("labelFermentables")
        self.gridLayout_7.addWidget(self.labelFermentables, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableViewF = QtWidgets.QTableView(self.widgetEditeur)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewF.sizePolicy().hasHeightForWidth())
        self.tableViewF.setSizePolicy(sizePolicy)
        self.tableViewF.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableViewF.setAlternatingRowColors(True)
        self.tableViewF.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableViewF.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewF.setShowGrid(False)
        self.tableViewF.setGridStyle(QtCore.Qt.NoPen)
        self.tableViewF.setObjectName("tableViewF")
        self.tableViewF.horizontalHeader().setCascadingSectionResizes(True)
        self.tableViewF.horizontalHeader().setDefaultSectionSize(175)
        self.tableViewF.horizontalHeader().setStretchLastSection(True)
        self.tableViewF.verticalHeader().setVisible(False)
        self.tableViewF.verticalHeader().setDefaultSectionSize(22)
        self.tableViewF.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tableViewF)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widgetEditeur)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 6, 0, 1, 1)
        self.widgetIngredients.raise_()
        self.labelFermentables.raise_()
        self.label_8.raise_()
        self.gridLayout.addWidget(self.widgetEditeur, 1, 0, 1, 1)
        self.widgetProfile = QtWidgets.QWidget(self.page)
        self.widgetProfile.setStyleSheet("")
        self.widgetProfile.setObjectName("widgetProfile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widgetProfile)
        self.verticalLayout_6.setContentsMargins(30, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widgetProfile)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelRendement = QtWidgets.QLabel(self.widgetProfile)
        self.labelRendement.setObjectName("labelRendement")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelRendement)
        self.doubleSpinBoxRendemt = QtWidgets.QDoubleSpinBox(self.widgetProfile)
        self.doubleSpinBoxRendemt.setObjectName("doubleSpinBoxRendemt")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxRendemt)
        self.labelBoil = QtWidgets.QLabel(self.widgetProfile)
        self.labelBoil.setObjectName("labelBoil")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBoil)
        self.spinBoxBoil = QtWidgets.QSpinBox(self.widgetProfile)
        self.spinBoxBoil.setMaximum(999)
        self.spinBoxBoil.setSingleStep(10)
        self.spinBoxBoil.setObjectName("spinBoxBoil")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxBoil)
        self.label_2Volume = QtWidgets.QLabel(self.widgetProfile)
        self.label_2Volume.setObjectName("label_2Volume")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2Volume)
        self.doubleSpinBox_2Volume = QtWidgets.QDoubleSpinBox(self.widgetProfile)
        self.doubleSpinBox_2Volume.setObjectName("doubleSpinBox_2Volume")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2Volume)
        self.pushButtonVolMore = QtWidgets.QPushButton(self.widgetProfile)
        self.pushButtonVolMore.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVolMore.setIcon(icon2)
        self.pushButtonVolMore.setCheckable(True)
        self.pushButtonVolMore.setObjectName("pushButtonVolMore")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButtonVolMore)
        self.verticalLayout_6.addLayout(self.formLayout_4)
        self.widgetVol = QtWidgets.QWidget(self.widgetProfile)
        self.widgetVol.setObjectName("widgetVol")
        self.formLayout_5 = QtWidgets.QFormLayout(self.widgetVol)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.widgetVol)
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBoxVolPre = QtWidgets.QDoubleSpinBox(self.widgetVol)
        self.doubleSpinBoxVolPre.setMaximum(999.0)
        self.doubleSpinBoxVolPre.setSingleStep(10.0)
        self.doubleSpinBoxVolPre.setObjectName("doubleSpinBoxVolPre")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxVolPre)
        self.labelSG = QtWidgets.QLabel(self.widgetVol)
        self.labelSG.setObjectName("labelSG")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelSG)
        self.label_2 = QtWidgets.QLabel(self.widgetVol)
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_6.addWidget(self.widgetVol)
        self.pushButtonRecipeNotes = QtWidgets.QPushButton(self.widgetProfile)
        self.pushButtonRecipeNotes.setObjectName("pushButtonRecipeNotes")
        self.verticalLayout_6.addWidget(self.pushButtonRecipeNotes)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 35, -1, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widgetProfile)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, 35)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.labelOG = QtWidgets.QLabel(self.widgetProfile)
        self.labelOG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOG.setObjectName("labelOG")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelOG)
        self.labelOGV = QtWidgets.QLabel(self.widgetProfile)
        self.labelOGV.setText("")
        self.labelOGV.setObjectName("labelOGV")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelOGV)
        self.labelFG = QtWidgets.QLabel(self.widgetProfile)
        self.labelFG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFG.setObjectName("labelFG")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelFG)
        self.labelFGV = QtWidgets.QLabel(self.widgetProfile)
        self.labelFGV.setText("")
        self.labelFGV.setObjectName("labelFGV")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelFGV)
        self.labelEBC = QtWidgets.QLabel(self.widgetProfile)
        self.labelEBC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEBC.setObjectName("labelEBC")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelEBC)
        self.labelEBCV = QtWidgets.QLabel(self.widgetProfile)
        self.labelEBCV.setText("")
        self.labelEBCV.setObjectName("labelEBCV")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelEBCV)
        self.labelIBU = QtWidgets.QLabel(self.widgetProfile)
        self.labelIBU.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelIBU.setObjectName("labelIBU")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelIBU)
        self.labelIBUV = QtWidgets.QLabel(self.widgetProfile)
        self.labelIBUV.setText("")
        self.labelIBUV.setObjectName("labelIBUV")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelIBUV)
        self.labelAlc = QtWidgets.QLabel(self.widgetProfile)
        self.labelAlc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAlc.setObjectName("labelAlc")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelAlc)
        self.labelAlcv = QtWidgets.QLabel(self.widgetProfile)
        self.labelAlcv.setText("")
        self.labelAlcv.setObjectName("labelAlcv")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelAlcv)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widgetProfile)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetColor = QtWidgets.QWidget(self.widgetProfile)
        self.widgetColor.setMinimumSize(QtCore.QSize(30, 10))
        self.widgetColor.setStyleSheet("")
        self.widgetColor.setObjectName("widgetColor")
        self.verticalLayout.addWidget(self.widgetColor)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widgetProfile, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listViewBiblio = QtWidgets.QListView(self.widget)
        self.listViewBiblio.setStyleSheet("background-color: rgb(116, 116, 116);\n"
"color: rgb(255, 255, 255);")
        self.listViewBiblio.setDragEnabled(True)
        self.listViewBiblio.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listViewBiblio.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listViewBiblio.setMovement(QtWidgets.QListView.Free)
        self.listViewBiblio.setFlow(QtWidgets.QListView.LeftToRight)
        self.listViewBiblio.setViewMode(QtWidgets.QListView.IconMode)
        self.listViewBiblio.setObjectName("listViewBiblio")
        self.gridLayout_3.addWidget(self.listViewBiblio, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textEditRecipeNotes = QtWidgets.QTextEdit(self.page_3)
        self.textEditRecipeNotes.setObjectName("textEditRecipeNotes")
        self.gridLayout_5.addWidget(self.textEditRecipeNotes, 0, 0, 1, 1)
        self.buttonBoxRecipeNotes = QtWidgets.QDialogButtonBox(self.page_3)
        self.buttonBoxRecipeNotes.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxRecipeNotes.setObjectName("buttonBoxRecipeNotes")
        self.gridLayout_5.addWidget(self.buttonBoxRecipeNotes, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listWidgetMashProfiles = QtWidgets.QListWidget(self.page_4)
        self.listWidgetMashProfiles.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetMashProfiles.setProperty("isWrapping", False)
        self.listWidgetMashProfiles.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidgetMashProfiles.setObjectName("listWidgetMashProfiles")
        self.verticalLayout_8.addWidget(self.listWidgetMashProfiles)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonRemoveProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonRemoveProfile.setEnabled(False)
        self.pushButtonRemoveProfile.setObjectName("pushButtonRemoveProfile")
        self.horizontalLayout_9.addWidget(self.pushButtonRemoveProfile)
        self.pushButtonNewProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonNewProfile.setObjectName("pushButtonNewProfile")
        self.horizontalLayout_9.addWidget(self.pushButtonNewProfile)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.widget1 = QtWidgets.QWidget(self.page_4)
        self.widget1.setMinimumSize(QtCore.QSize(500, 0))
        self.widget1.setObjectName("widget1")
        self.formLayout_7 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(50, -1, 50, -1)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setObjectName("label_16")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.labelMashName = QtWidgets.QLabel(self.widget1)
        self.labelMashName.setObjectName("labelMashName")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelMashName)
        self.label_17 = QtWidgets.QLabel(self.widget1)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.labelMashPh = QtWidgets.QLabel(self.widget1)
        self.labelMashPh.setObjectName("labelMashPh")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelMashPh)
        self.label_24 = QtWidgets.QLabel(self.widget1)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.labelMashSpargeTemp = QtWidgets.QLabel(self.widget1)
        self.labelMashSpargeTemp.setObjectName("labelMashSpargeTemp")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelMashSpargeTemp)
        self.pushButtonMashEdit = QtWidgets.QPushButton(self.widget1)
        self.pushButtonMashEdit.setEnabled(False)
        self.pushButtonMashEdit.setObjectName("pushButtonMashEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButtonMashEdit)
        self.horizontalLayout_14.addWidget(self.widget1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetSteps = QtWidgets.QListWidget(self.page_4)
        self.listWidgetSteps.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetSteps.setObjectName("listWidgetSteps")
        self.verticalLayout_2.addWidget(self.listWidgetSteps)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonStepRemove = QtWidgets.QPushButton(self.page_4)
        self.pushButtonStepRemove.setEnabled(False)
        self.pushButtonStepRemove.setObjectName("pushButtonStepRemove")
        self.horizontalLayout_6.addWidget(self.pushButtonStepRemove)
        self.pushButtonNewStep = QtWidgets.QPushButton(self.page_4)
        self.pushButtonNewStep.setObjectName("pushButtonNewStep")
        self.horizontalLayout_6.addWidget(self.pushButtonNewStep)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.widget2 = QtWidgets.QWidget(self.page_4)
        self.widget2.setMinimumSize(QtCore.QSize(500, 0))
        self.widget2.setObjectName("widget2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.widget2)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(50, -1, 50, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.labelStepName = QtWidgets.QLabel(self.widget2)
        self.labelStepName.setObjectName("labelStepName")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelStepName)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setObjectName("label_10")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.labelStepType = QtWidgets.QLabel(self.widget2)
        self.labelStepType.setObjectName("labelStepType")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelStepType)
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.labelStepTime = QtWidgets.QLabel(self.widget2)
        self.labelStepTime.setObjectName("labelStepTime")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelStepTime)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.labelStepTemp = QtWidgets.QLabel(self.widget2)
        self.labelStepTemp.setObjectName("labelStepTemp")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelStepTemp)
        self.pushButtonStepEdit = QtWidgets.QPushButton(self.widget2)
        self.pushButtonStepEdit.setEnabled(False)
        self.pushButtonStepEdit.setObjectName("pushButtonStepEdit")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonStepEdit)
        self.horizontalLayout_8.addWidget(self.widget2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.buttonBoxMashDetails = QtWidgets.QDialogButtonBox(self.page_4)
        self.buttonBoxMashDetails.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxMashDetails.setObjectName("buttonBoxMashDetails")
        self.horizontalLayout_15.addWidget(self.buttonBoxMashDetails)
        self.pushButtonSaveProfile = QtWidgets.QPushButton(self.page_4)
        self.pushButtonSaveProfile.setObjectName("pushButtonSaveProfile")
        self.horizontalLayout_15.addWidget(self.pushButtonSaveProfile)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.gridLayout_8.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem9, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.formLayoutSparge = QtWidgets.QFormLayout()
        self.formLayoutSparge.setObjectName("formLayoutSparge")
        self.labelSparge1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelSparge1.setObjectName("labelSparge1")
        self.formLayoutSparge.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSparge1)
        self.labelSparge2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelSparge2.setObjectName("labelSparge2")
        self.formLayoutSparge.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSparge2)
        self.labelSpargeVol = QtWidgets.QLabel(self.groupBox_2)
        self.labelSpargeVol.setObjectName("labelSpargeVol")
        self.formLayoutSparge.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelSpargeVol)
        self.labelSpargeTemp = QtWidgets.QLabel(self.groupBox_2)
        self.labelSpargeTemp.setObjectName("labelSpargeTemp")
        self.formLayoutSparge.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelSpargeTemp)
        self.labelNoSparge = QtWidgets.QLabel(self.groupBox_2)
        self.labelNoSparge.setMinimumSize(QtCore.QSize(100, 0))
        self.labelNoSparge.setStyleSheet("background-color: rgb(255, 255, 196);")
        self.labelNoSparge.setObjectName("labelNoSparge")
        self.formLayoutSparge.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelNoSparge)
        self.gridLayout_10.addLayout(self.formLayoutSparge, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.page_5)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.labelPreBoilGravity = QtWidgets.QLabel(self.groupBox)
        self.labelPreBoilGravity.setObjectName("labelPreBoilGravity")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelPreBoilGravity)
        self.labelPreBoilVol = QtWidgets.QLabel(self.groupBox)
        self.labelPreBoilVol.setText("")
        self.labelPreBoilVol.setObjectName("labelPreBoilVol")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelPreBoilVol)
        self.gridLayout_9.addLayout(self.formLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.groupBox)
        self.gridLayout_12.addLayout(self.horizontalLayout_18, 3, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.page_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.tableWidgetStepsBrewday = QtWidgets.QTableWidget(self.page_5)
        self.tableWidgetStepsBrewday.setMaximumSize(QtCore.QSize(123456, 200))
        self.tableWidgetStepsBrewday.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidgetStepsBrewday.setAlternatingRowColors(True)
        self.tableWidgetStepsBrewday.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetStepsBrewday.setShowGrid(False)
        self.tableWidgetStepsBrewday.setRowCount(0)
        self.tableWidgetStepsBrewday.setColumnCount(5)
        self.tableWidgetStepsBrewday.setObjectName("tableWidgetStepsBrewday")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(4, item)
        self.tableWidgetStepsBrewday.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetStepsBrewday.horizontalHeader().setDefaultSectionSize(175)
        self.tableWidgetStepsBrewday.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetStepsBrewday.verticalHeader().setVisible(False)
        self.tableWidgetStepsBrewday.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetStepsBrewday.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_12.addWidget(self.tableWidgetStepsBrewday)
        self.labelWarningBiab = QtWidgets.QLabel(self.page_5)
        self.labelWarningBiab.setMinimumSize(QtCore.QSize(0, 20))
        self.labelWarningBiab.setStyleSheet("background-color: rgb(255, 255, 196);")
        self.labelWarningBiab.setObjectName("labelWarningBiab")
        self.verticalLayout_12.addWidget(self.labelWarningBiab)
        self.labelNoDecoction = QtWidgets.QLabel(self.page_5)
        self.labelNoDecoction.setMinimumSize(QtCore.QSize(0, 20))
        self.labelNoDecoction.setStyleSheet("background-color: rgb(255, 255, 196);")
        self.labelNoDecoction.setObjectName("labelNoDecoction")
        self.verticalLayout_12.addWidget(self.labelNoDecoction)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.pushButtonAdjustStep = QtWidgets.QPushButton(self.page_5)
        self.pushButtonAdjustStep.setObjectName("pushButtonAdjustStep")
        self.horizontalLayout_16.addWidget(self.pushButtonAdjustStep)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.gridLayout_12.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.radioButtonClassicBrew = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonClassicBrew.setChecked(True)
        self.radioButtonClassicBrew.setObjectName("radioButtonClassicBrew")
        self.horizontalLayout_17.addWidget(self.radioButtonClassicBrew)
        self.radioButtonBIAB = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonBIAB.setObjectName("radioButtonBIAB")
        self.horizontalLayout_17.addWidget(self.radioButtonBIAB)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.gridLayout_11.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem12, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem13, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1293, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFichier = QtWidgets.QMenu(self.menuBar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdition = QtWidgets.QMenu(self.menuBar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuOutils = QtWidgets.QMenu(self.menuBar)
        self.menuOutils.setObjectName("menuOutils")
        self.menuVue = QtWidgets.QMenu(self.menuBar)
        self.menuVue.setObjectName("menuVue")
        self.menuAide = QtWidgets.QMenu(self.menuBar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOuvrir.setIcon(icon3)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon4)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_Sous = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Sous.setObjectName("actionEnregistrer_Sous")
        self.actionQuitter_2 = QtWidgets.QAction(MainWindow)
        self.actionQuitter_2.setObjectName("actionQuitter_2")
        self.actionOuvrir_2 = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_2.setObjectName("actionOuvrir_2")
        self.actionEditGrains = QtWidgets.QAction(MainWindow)
        self.actionEditGrains.setObjectName("actionEditGrains")
        self.actionEditHoublons = QtWidgets.QAction(MainWindow)
        self.actionEditHoublons.setObjectName("actionEditHoublons")
        self.actionEditDivers = QtWidgets.QAction(MainWindow)
        self.actionEditDivers.setObjectName("actionEditDivers")
        self.actionEditLevures = QtWidgets.QAction(MainWindow)
        self.actionEditLevures.setObjectName("actionEditLevures")
        self.actionNouvelle_recette = QtWidgets.QAction(MainWindow)
        self.actionNouvelle_recette.setIcon(icon2)
        self.actionNouvelle_recette.setObjectName("actionNouvelle_recette")
        self.actionCorrectionDens = QtWidgets.QAction(MainWindow)
        self.actionCorrectionDens.setObjectName("actionCorrectionDens")
        self.actionCalculAlc = QtWidgets.QAction(MainWindow)
        self.actionCalculAlc.setObjectName("actionCalculAlc")
        self.actionImprimer = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer.setIcon(icon6)
        self.actionImprimer.setObjectName("actionImprimer")
        self.actionDilution = QtWidgets.QAction(MainWindow)
        self.actionDilution.setObjectName("actionDilution")
        self.actionEvaporation = QtWidgets.QAction(MainWindow)
        self.actionEvaporation.setObjectName("actionEvaporation")
        self.actionExporterHtml = QtWidgets.QAction(MainWindow)
        self.actionExporterHtml.setObjectName("actionExporterHtml")
        self.actionPaliers = QtWidgets.QAction(MainWindow)
        self.actionPaliers.setObjectName("actionPaliers")
        self.actionRestaurerIngredients = QtWidgets.QAction(MainWindow)
        self.actionRestaurerIngredients.setObjectName("actionRestaurerIngredients")
        self.actionRecharger = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecharger.setIcon(icon7)
        self.actionRecharger.setObjectName("actionRecharger")
        self.actionSwitch = QtWidgets.QAction(MainWindow)
        self.actionSwitch.setObjectName("actionSwitch")
        self.actionVueEditeur = QtWidgets.QAction(MainWindow)
        self.actionVueEditeur.setObjectName("actionVueEditeur")
        self.actionVueBibliotheque = QtWidgets.QAction(MainWindow)
        self.actionVueBibliotheque.setObjectName("actionVueBibliotheque")
        self.actionVueEditeurToolBar = QtWidgets.QAction(MainWindow)
        self.actionVueEditeurToolBar.setCheckable(True)
        self.actionVueEditeurToolBar.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueEditeurToolBar.setIcon(icon8)
        self.actionVueEditeurToolBar.setObjectName("actionVueEditeurToolBar")
        self.actionVueBibliothequeToolBar = QtWidgets.QAction(MainWindow)
        self.actionVueBibliothequeToolBar.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Images/library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueBibliothequeToolBar.setIcon(icon9)
        self.actionVueBibliothequeToolBar.setObjectName("actionVueBibliothequeToolBar")
        self.actionEnregistrerToolBar = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrerToolBar.setIcon(icon10)
        self.actionEnregistrerToolBar.setObjectName("actionEnregistrerToolBar")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.toolBar.addAction(self.actionVueEditeurToolBar)
        self.toolBar.addAction(self.actionVueBibliothequeToolBar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEnregistrerToolBar)
        self.toolBar.addAction(self.actionImprimer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNouvelle_recette)
        self.toolBar.addAction(self.actionRecharger)
        self.menuFichier.addAction(self.actionOuvrir_2)
        self.menuFichier.addAction(self.actionNouvelle_recette)
        self.menuFichier.addAction(self.actionRecharger)
        self.menuFichier.addAction(self.actionImprimer)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_Sous)
        self.menuFichier.addAction(self.actionExporterHtml)
        self.menuFichier.addAction(self.actionQuitter_2)
        self.menuEdition.addAction(self.actionEditGrains)
        self.menuEdition.addAction(self.actionEditHoublons)
        self.menuEdition.addAction(self.actionEditDivers)
        self.menuEdition.addAction(self.actionEditLevures)
        self.menuEdition.addAction(self.actionRestaurerIngredients)
        self.menuEdition.addAction(self.actionPreferences)
        self.menuOutils.addAction(self.actionCorrectionDens)
        self.menuOutils.addAction(self.actionCalculAlc)
        self.menuOutils.addAction(self.actionDilution)
        self.menuOutils.addAction(self.actionEvaporation)
        self.menuOutils.addAction(self.actionPaliers)
        self.menuVue.addAction(self.actionVueEditeur)
        self.menuVue.addAction(self.actionVueBibliotheque)
        self.menuAide.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFichier.menuAction())
        self.menuBar.addAction(self.menuVue.menuAction())
        self.menuBar.addAction(self.menuEdition.menuAction())
        self.menuBar.addAction(self.menuOutils.menuAction())
        self.menuBar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JolieBulle"))
        self.checkBoxIng.setText(_translate("MainWindow", "Ajuster les ingrédients (verrouiller le profil)"))
        self.pushButtonChangeIngredients.setText(_translate("MainWindow", "Ajouter/Enlever"))
        self.pushButtonMashDetails.setText(_translate("MainWindow", "Détails"))
        self.pushButtonBrewdayMode.setText(_translate("MainWindow", "Mode Brassage"))
        self.pushButtonAjouter_2.setText(_translate("MainWindow", "Ajouter Grain"))
        self.pushButtonAjouterH.setText(_translate("MainWindow", "Ajouter Houblon"))
        self.pushButtonAjouterM.setText(_translate("MainWindow", "Ajouter Divers"))
        self.pushButtonAjouterY.setText(_translate("MainWindow", "Ajouter Levure"))
        self.pushButtonEnlever.setText(_translate("MainWindow", "Enlever"))
        self.labelRecette.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nom de la recette :</span></p></body></html>"))
        self.labelGenre.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Genre :</span></p></body></html>"))
        self.pushButtonChangerStyle.setToolTip(_translate("MainWindow", "Liste de styles BJCP"))
        self.label_3.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brasseur :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Type :</span></p></body></html>"))
        self.labelFermentables.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Ingredients : </span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brassage :</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">CONTEXTE</span></p></body></html>"))
        self.labelRendement.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Rendement (%)</span></p></body></html>"))
        self.labelBoil.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Ebullition (min)</span></p></body></html>"))
        self.label_2Volume.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Volume (L)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Volume pré-ébullition</span></p></body></html>"))
        self.labelSG.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Densité  pré-ébullition :</span></p></body></html>"))
        self.pushButtonRecipeNotes.setText(_translate("MainWindow", "Notes"))
        self.label_6.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">PROFIL</span></p></body></html>"))
        self.labelOG.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Densité Initiale :</span></p></body></html>"))
        self.labelFG.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Densité Finale :</span></p></body></html>"))
        self.labelEBC.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">EBC :</span></p></body></html>"))
        self.labelIBU.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">IBU :</span></p></body></html>"))
        self.labelAlc.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Alc :</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:600;\">TEINTE</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Profils de brassage :</span></p></body></html>"))
        self.pushButtonRemoveProfile.setText(_translate("MainWindow", "Enlever"))
        self.pushButtonNewProfile.setText(_translate("MainWindow", "Nouveau profil"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Nom :</span></p></body></html>"))
        self.labelMashName.setText(_translate("MainWindow", "Aucun"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">pH :</span></p></body></html>"))
        self.labelMashPh.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Rinçage :</span></p></body></html>"))
        self.labelMashSpargeTemp.setText(_translate("MainWindow", "0 °C"))
        self.pushButtonMashEdit.setText(_translate("MainWindow", "Modifier"))
        self.label_14.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Paliers :</span></p></body></html>"))
        self.pushButtonStepRemove.setText(_translate("MainWindow", "Enlever"))
        self.pushButtonNewStep.setText(_translate("MainWindow", "Nouveau palier"))
        self.label_9.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nom :</span></p></body></html>"))
        self.labelStepName.setText(_translate("MainWindow", "Aucun"))
        self.label_10.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Type :</span></p></body></html>"))
        self.labelStepType.setText(_translate("MainWindow", "Aucun"))
        self.label_11.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Durée :</span></p></body></html>"))
        self.labelStepTime.setText(_translate("MainWindow", "0 min"))
        self.label_12.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Température :</span></p></body></html>"))
        self.labelStepTemp.setText(_translate("MainWindow", "0 °C"))
        self.pushButtonStepEdit.setText(_translate("MainWindow", "Modifier"))
        self.pushButtonSaveProfile.setText(_translate("MainWindow", "Enregistrer les profils"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Rinçage"))
        self.labelSparge1.setText(_translate("MainWindow", "Volume de rinçage :"))
        self.labelSparge2.setText(_translate("MainWindow", "Température de rinçage :"))
        self.labelSpargeVol.setText(_translate("MainWindow", "0"))
        self.labelSpargeTemp.setText(_translate("MainWindow", "0"))
        self.labelNoSparge.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">   Pas de rinçage en BIAB</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Pré-ébullition"))
        self.label_18.setText(_translate("MainWindow", "Volume théorique pré-ébullition :"))
        self.label_19.setText(_translate("MainWindow", "Densité pré-ébullition :"))
        self.labelPreBoilGravity.setText(_translate("MainWindow", "1.000"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Volumes d\'eau</span></p></body></html>"))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Palier"))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Volume d\'eau"))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Température de l\'eau"))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ratio"))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Infos"))
        self.labelWarningBiab.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Le profil de brassage que vous utilisez n\'est pas adapté au BIAB. Vous ne devriez utiliser qu\'un seul palier d\'infusion.</span></p></body></html>"))
        self.labelNoDecoction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">JolieBulle ne prend pas encore en charge les décoctions. Pas encore !</span></p></body></html>"))
        self.pushButtonAdjustStep.setText(_translate("MainWindow", "Ajuster"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Méthode de brassage"))
        self.radioButtonClassicBrew.setText(_translate("MainWindow", "Classique"))
        self.radioButtonBIAB.setText(_translate("MainWindow", "Volume complet (BIAB)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition"))
        self.menuOutils.setTitle(_translate("MainWindow", "Outils"))
        self.menuVue.setTitle(_translate("MainWindow", "Vue"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionAbout.setText(_translate("MainWindow", "A propos"))
        self.actionEnregistrer.setText(_translate("MainWindow", "&Enregistrer"))
        self.actionEnregistrer_Sous.setText(_translate("MainWindow", "Enregistrer &sous"))
        self.actionQuitter_2.setText(_translate("MainWindow", "Quitter"))
        self.actionOuvrir_2.setText(_translate("MainWindow", "&Ouvrir"))
        self.actionEditGrains.setText(_translate("MainWindow", "Editer la base de Grains"))
        self.actionEditHoublons.setText(_translate("MainWindow", "Editer la base de Houblons"))
        self.actionEditDivers.setText(_translate("MainWindow", "Editer la base de Divers"))
        self.actionEditLevures.setText(_translate("MainWindow", "Editer la base de Levures"))
        self.actionNouvelle_recette.setText(_translate("MainWindow", "Nouvelle recette"))
        self.actionCorrectionDens.setText(_translate("MainWindow", "Correction densimètre"))
        self.actionCalculAlc.setText(_translate("MainWindow", "Calcul taux d\'alcool"))
        self.actionImprimer.setText(_translate("MainWindow", "Imprimer"))
        self.actionDilution.setText(_translate("MainWindow", "Dilution"))
        self.actionEvaporation.setText(_translate("MainWindow", "Evaporation"))
        self.actionExporterHtml.setText(_translate("MainWindow", "Exporter vers html"))
        self.actionPaliers.setText(_translate("MainWindow", "Assistant paliers"))
        self.actionRestaurerIngredients.setText(_translate("MainWindow", "Restaurer la base des ingrédients"))
        self.actionRecharger.setText(_translate("MainWindow", "Recharger"))
        self.actionSwitch.setText(_translate("MainWindow", "switch"))
        self.actionVueEditeur.setText(_translate("MainWindow", "Editeur de recettes"))
        self.actionVueBibliotheque.setText(_translate("MainWindow", "Bibliothèque de recettes"))
        self.actionVueBibliotheque.setToolTip(_translate("MainWindow", "Bibiliothèque de recettes"))
        self.actionVueEditeurToolBar.setText(_translate("MainWindow", "Editeur"))
        self.actionVueBibliothequeToolBar.setText(_translate("MainWindow", "Bibiliothèque"))
        self.actionVueBibliothequeToolBar.setToolTip(_translate("MainWindow", "Bibiliothèque de recettes"))
        self.actionEnregistrerToolBar.setText(_translate("MainWindow", "&Enregistrer"))
        self.actionPreferences.setText(_translate("MainWindow", "Préférences"))

